[package]
name = "ufire_ise"
version = "0.9.0"
authors = ["Justin Decker <justind000@gmail.com>"]
readme = "README.md"
[lib]
name = "ufire_ise"
path = "src/lib.rs"

[[bin]]
name = "ufire_ise_bin"
path = "src/main.rs"

[dependencies]
i2cdev = "0.3.2"
byteorder = "1"
